### PR TITLE
WannaCry Ransomware

### PR DESCRIPTION
**Pull request by Yiep**

### CODE REVIEW

**Comment by fsacer** [comment]
This does not include the worm!

**Comment by polymetric1** [comment]
Is it not in the .zip file?

**Comment by fsacer** [comment]
the worm part is here https://www.hybrid-analysis.com/sample/24d004a104d4d54034dbcffc2a4b19a11f39008a575aa614ea04703480b1022c?environmentId=100 wih diffrent hash

**Comment by fsacer** [comment]
Also is there any effort of reverse engineering here?

**Pull request merged**
